import { auth } from '../firebase';
import type { GeneratedImage, ImageSize } from '../types';

const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve((reader.result as string).split(',')[1]);
    reader.onerror = (error) => reject(error);
  });
};

export const generateImageVariations = async (
  imageFile: File | null,
  prompts: string[],
  referenceImageFiles: File[],
  maskFile: File | null,
  aspectRatio: string,
  imageSize: ImageSize = '1K',
  systemApiKey: string | null = null,
  globalSettings: any = null
): Promise<GeneratedImage[]> => {
  const currentUser = auth.currentUser;
  if (!currentUser) {
    throw new Error("You must be logged in to generate images.");
  }

  // Get Firebase ID Token (for rate limiting on server)
  const idToken = await currentUser.getIdToken();

  const generateSingleImage = async (prompt: string): Promise<GeneratedImage> => {
    try {
      // 1. Call server-side rate limit endpoint first
      const rateLimitResponse = await fetch('/api/rate-limit', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${idToken}`,
        },
      });

      if (!rateLimitResponse.ok) {
        const errorData = await rateLimitResponse.json();
        throw new Error(errorData.error || "Rate limit exceeded.");
      }

      const mainImage = imageFile
        ? { data: await fileToBase64(imageFile), mimeType: imageFile.type }
        : null;
      const refs = await Promise.all(
        (referenceImageFiles || []).map(async (file) => ({
          data: await fileToBase64(file),
          mimeType: file.type
        }))
      );

      const response = await fetch('/api/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${idToken}`,
        },
        body: JSON.stringify({
          prompt,
          aspectRatio,
          imageSize,
          provider: globalSettings?.activeProvider || 'gemini',
          geminiModel: globalSettings?.geminiModel,
          openaiModel: globalSettings?.openaiModel,
          seedanceModel: globalSettings?.seedanceModel,
          seedanceBaseUrl: globalSettings?.seedanceBaseUrl,
          seedreamModel: globalSettings?.seedreamModel,
          seedreamBaseUrl: globalSettings?.seedreamBaseUrl,
          mainImage,
          referenceImages: refs
        })
      });

      const rawBody = await response.text();
      let responseData: any = {};
      try {
        responseData = rawBody ? JSON.parse(rawBody) : {};
      } catch (error) {
        responseData = {};
      }
      if (!response.ok) {
        const preview = String(rawBody || '').slice(0, 180).replace(/\s+/g, ' ').trim();
        const fallbackMessage = rawBody && rawBody.startsWith('<')
          ? `Backend returned non-JSON response (HTTP ${response.status}). Preview: ${preview || 'empty body'}`
          : `Backend error (HTTP ${response.status}): ${preview || 'empty body'}`;
        throw new Error(responseData.error || fallbackMessage || 'Generation failed.');
      }

      const imageBase64 = responseData.imageBase64;
      if (!imageBase64) {
        throw new Error("No image was generated by the model.");
      }

      return {
        prompt,
        imageUrl: `data:image/png;base64,${imageBase64}`,
        text: responseData.text || '',
        promptTokens: responseData.promptTokens || 0,
        completionTokens: responseData.completionTokens || 0,
        totalTokens: responseData.totalTokens || 0
      };

    } catch (error: any) {
      console.error(`Error generating image for prompt "${prompt}":`, error);
      
      let userMessage = error.message || 'An unknown error occurred.';
      const provider = String(globalSettings?.activeProvider || 'gemini');

      // Handle specific API errors (Gemini-only messages — do not mislabel Seedream/OpenAI)
      if (userMessage.includes('429') || userMessage.toLowerCase().includes('quota exceeded') || userMessage.includes('RESOURCE_EXHAUSTED')) {
        if (provider === 'gemini') {
          userMessage = "Hết hạn mức API (429 Quota Exceeded): Tài khoản Miễn phí của bạn đã hết lượt sử dụng. Vui lòng thử lại sau vài phút (giới hạn phút) hoặc vào ngày mai (giới hạn ngày). Để sử dụng không giới hạn, vui lòng nhấn nút 'Select API Key' và chọn một Key từ Google Cloud dự án có tính phí (Paid project).";
        }
      } else if (
        provider === 'gemini' &&
        (userMessage.includes('403') || userMessage.toLowerCase().includes('forbidden'))
      ) {
        userMessage = "Lỗi API (403 Forbidden): Model Gemini image yêu cầu API Key trả phí (Paid) từ Google Cloud. Hoặc chọn SEEDREAM · Dola-Seedream-5.0-lite / ByteDance-Seedream-4.5 trên dropdown (cần SEEDREAM_API_KEY).";
      } else if (userMessage.includes('Requested entity was not found')) {
        if (provider === 'gemini') {
          userMessage = "Lỗi API: API Key đã chọn có thể không hợp lệ hoặc model không khả dụng cho Key này. Vui lòng thử chọn lại API Key.";
        }
      }
      
      return {
        prompt,
        imageUrl: 'error',
        text: userMessage,
        promptTokens: 0,
        completionTokens: 0,
        totalTokens: 0
      };
    }
  };

  const generationPromises = prompts.map(prompt => generateSingleImage(prompt));
  return Promise.all(generationPromises);
};
